#!/bin/bash

# Help: Shows this help.

# Extracts help for the various subcommands by searching or text starting
# with '# Help: '.

function mac_help() {
  echo "Usage: mac <subcommand>"
  echo ""
  echo "Commands:"
  echo ""
  ls $DOTMAC/.bin/mac-* | while read -r script_path; do
    command_name="$(basename "$script_path" | cut -c 5-)"
    if mac_help_exists "$script_path"; then
      local help="$(mac_help_extract "$script_path")"
      first_line=true
      while read -r line; do
        if $first_line; then
          printf "    %-13s - %s\n" "$command_name" "$line"
          first_line=false
        else
          printf "    %-13s   %s\n" "" "$line"
        fi
      done <<< "$help"
    fi
  done
}

function mac_help_exists() {
  local script_path="$1"

  local help_lines="$(grep -c "^# Help: " "$script_path")"

  if [ "$help_lines" = "0" ]; then
    return 1
  else
    return 0
  fi
}

function mac_help_extract() {
  local script_path="$1"

  grep "^# Help: " "$script_path" | cut -c 9-
}

mac_help
